//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesaj_portali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public int mesajId { get; set; }
        public int gonderenId { get; set; }
        public int aliciId { get; set; }
        public string mesajText { get; set; }
        public System.DateTime mesajTarih { get; set; }
        public int mesajSohbetId { get; set; }
    
        public virtual Uye Uye { get; set; }
        public virtual Uye Uye1 { get; set; }
        public virtual Sohbet Sohbet { get; set; }
    }
}
